### ISSUE TITLE
Consider switching to gitea ?

### ISSUE THREAD

**Issue by mbugeia** [YunoHost-Apps/gogs_ynh#11]
https://github.com/go-gitea/gitea

Fork of Gogs, community driven. 

My opinion: it's a little too soon to decide but they appear to merge a lot of things. Maybe in 2-3 releases.

**Comment by M5oul** [comment]
Nice. I didn't see this ticket.
Here is some interesting doc:

- [Welcome to Gitea ](https://blog.gitea.io/2016/12/welcome-to-gitea)
- [Releases](https://github.com/go-gitea/gitea/releases)

**Comment by stevenroose** [comment]
I actually moved my focus from Gogs to Gitea for a while now. I don't have it running yet, but I'm following the development. The team is quite active and they have some very good devs. 

The problem with Gogs is that it's a one man show with only one guys with commit access. Unknwon disappeared from time to time, basically halting development for months.

**Comment by mbugeia** [comment]
True, but Gitea didn't release anything major for now while Gogs is still active (v0.10 is out).

**Comment by Salamandar** [comment]
Gitea 1.0.0 was released on 24 Dec 2016, and the last release is v1.1.2 (12 Jun 2017). Seems pretty active to me ;)

* Gogs : https://screenshots.firefox.com/DkVClXuC5sX8PzWz/github.com
vs
* Gitea : https://screenshots.firefox.com/2XvKDQodBfMsOlDU/github.com

**Comment by optikfluffel** [comment]
A little update:

## Gitea:
[![Gitea Last Month](https://user-images.githubusercontent.com/379915/30375991-e6e8c8b0-988a-11e7-9abf-1c4eb39f608c.png)](https://github.com/go-gitea/gitea/pulse/monthly)

## Gogs:
[![Gogs Last Month](https://user-images.githubusercontent.com/379915/30376006-f5c96b64-988a-11e7-878b-d818acc5590e.png)](https://github.com/gogits/gogs/pulse/monthly)

**Comment by jbz-dev** [comment]
For those who want to test I'm building a repo for Gitea on YunoHost.

https://github.com/Bridouz/gitea_ynh

**Comment by SuperSandro2000** [comment]
In the meantime you can do it via the redirection plugin and setup gitea manually.
You only need to do the inital gitea setup via a ssh tunnel and point gitea to domain.com/gitea/. Got it working with the help of these two gages:
https://wiki.archlinux.org/index.php/Gitea#Configure_nginx_as_reverse_proxy
https://gogs.io/docs/intro/faqs

**Comment by Josue-T** [comment]
Hello,

When I see all new feature available in gitea (see https://docs.gitea.io/en-us/comparison/), I'm really thinking about a migrating to gitea. @Rafi594 what do you think about implementing in gitea a migration from gogs ? 

And for everybody what do you think about to give up Gogs and migrate definitely to gitea ?

In this case I could also help to maintain gitea.

**Comment by stilobique** [comment]
Only an issue comment, but Gogs don't support the LFS features.

**Comment by Josue-T** [comment]
Yes, and gitea support. But it's only one thing among many others things.

**Comment by anmol26s** [comment]
Please open an topic on the forum about it. Because it would be good to keep support for one of them. I am currently using Gogs. And if in community is more tilted towards Gitea then this is best time to choose one because in coming months many people will leave Github and migrate to other alternative. Preferred choice would be a maintained alternative.

**Comment by Salamandar** [comment]
I'm using the gitea_ynh for some time now.
The maintainer is quite reactive (pull requests are merged within the week) and it works without a hinch (with my PR ^^). 
I don't have the link to gitea_ynh right now, but it's hosted on framagit.

**Comment by SuperSandro2000** [comment]
This https://framagit.org/YunoHost-Apps/gitea_ynh ?

**Comment by anmol26s** [comment]
Looking at this document: https://docs.gitea.io/en-us/comparison/
I think we should move to Gitea. My decision depends on @Josue-T if he is willing to maintain Gogs despite of so cold and slow response from Gogs developer.

**Comment by Josue-T** [comment]
I made a topic on the forum here : https://forum.yunohost.org/t/gogs-migrate-to-gitea/5786

**Comment by Josue-T** [comment]
Hello,

I made a migration available here : https://framagit.org/YunoHost-Apps/gitea_ynh/merge_requests/38

So for now the idea it to migrate gitea and to depeciate gogs.
