### ISSUE TITLE
upgrade didn't works

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/gogs_ynh#12]
```bash
+ DESTDIR=/opt/gogs
+ REPO_PATH=/home/gogs/repositories
+ DATA_PATH=/home/gogs/data
+ '[' -d /etc/gogs ']'
+ sudo mkdir -p /home/gogs/repositories
++ ynh_app_setting_get gogs repopath
++ sudo yunohost app setting gogs repopath --output-as plain --quiet
+ old_repo_path=
+ sudo mv '/home/yunohost.app/gogs/*' /home/gogs/repositories
Warning: mv: cannot stat ‘/home/yunohost.app/gogs/*’: No such file or directory
Error: Unable to upgrade gogs
Error: No app to upgrade
```

**Comment by M5oul** [comment]
`/home/yunohost.app/gogs/` contains repositories.

**Comment by M5oul** [comment]
Ok, I bypassed it adding `[ ! -d /etc/gogs ]`.

**Comment by mbugeia** [comment]
From which version are you upgrading ?

**Comment by mbugeia** [comment]
There is at least 1 bug since /etc/gogs should be removed at the end of the if statement when migrating from the old package.

edit: wrong, i should read properly my code...

**Comment by M5oul** [comment]
I am upgrading from v0.9.71.

**Comment by mbugeia** [comment]
I'm not sure about the reason of your bug. The code seems logical to me. Is the directory /etc/gogs exist on your yunohost ?

**Comment by M5oul** [comment]
yep.

**Comment by M5oul** [comment]
My instance might have some relicats.
It might not happen to other people.
We could close it for now.

**Comment by mbugeia** [comment]
Yes you probably did an upgrade before with an unfinished version of the package ;)
