### ISSUE TITLE
Backup/restore issue

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/gogs_ynh#15]
When backuping the system, without taking gogs into account, `/home` is automatically backuped.
Gogs' data are stored on `/home/gogs/`.
That's can be a problem.
On my case, I am mirorring a project which have many builds releases.
Those builds are around 1Gb.
Finally, I can't make works the backup/restore because of free memory space issue with 8Gb SD card.
Furthermore, compression/decompression of tarball is very slow.

Why did this folder was choosed? Why not using `/home/yunohost.app/gogs`?

**Comment by mbugeia** [comment]
Regarding the use of /home/gogs I did answer the question here:
https://forum.yunohost.org/t/gogs-package-an-awesome-github-alternative/1127/16?u=tostaki

Regarding your issue, I find inconsistent that yunohost backup /home entirely, for me it should backup only what's needed and used by yunohost itself.

I'm not really for changing the directory now, it's always painful and it leave migration code in the package for an undefined period of time :/

**Comment by M5oul** [comment]
> Regarding your issue, I find inconsistent that yunohost backup /home entirely, for me it should backup only what's needed and used by yunohost itself.
>
> I'm not really for changing the directory now, it's always painful and it leave migration code in the package for an undefined period of time :/

Yep, you are right.
A ticket have to be opened on YunoHost bugtracker to be discuss.

**Comment by mbugeia** [comment]
And if `/home` is backed entirely, wouldn't the use of `/home/yunohost.app/gogs` have the same issue? (or maybe it's excluded?)

**Comment by M5oul** [comment]
It seems to be excluded, as for `/home/yunohost.backup`.

**Comment by M5oul** [comment]
- opi> Moul: ton soucis de gros backup, c'est un bug chez nous, ou c'est côté gogs ?                  
- Moul> opi, c’est lié : https://github.com/YunoHost-Apps/gogs_ynh/issues/15
- Moul> Après, c’est aussi une suggestion d’amélioration côté Gogs/Gitea : https://github.com/gogits/gogs/issues/4165  
- opi> Moul: je suis pour sauvegarder toutes les données moi
- Moul> ok
- Moul> Du coup, selon toi, Gogs devrait respecter la règle de mettre les données dans `/home/yunohost.app/$app` ?
- opi> Moul: pourquoi pas, ça peut permettre de l'exclure ou de le backuper spécifiquement non ?
- Moul> opi, oui, tout à fait.
