### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/gogs_ynh#18]
Hi all !

I have an issue while upgrading:

````
# LANG=C && yunohost app upgrade -u https://github.com/YunoHost-Apps/gogs_ynh gogs
Warning: mv: cannot stat '/home/yunohost.app/gogs/*': No such file or directory
Error: Unable to upgrade gogs
Error: No app to upgrade
````

I'm under Gogs Version: 0.9.71.0809 previously updated using the script.

Thanks !

Léo

**Comment by mbugeia** [comment]
Hi, it look similar to this https://github.com/YunoHost-Apps/gogs_ynh/issues/12 a workaround is to delete /etc/gogs 
But there is probably a bug in the upgrade script.

**Comment by LeOSW42** [comment]
Worked fine thanks

**Comment by mbugeia** [comment]
Let keep this issue open, it's indeed a bug ;)

**Comment by Josue-T** [comment]
I close this after https://github.com/YunoHost-Apps/gogs_ynh/commit/36a8e2b30e776a7d29028b7a60fb2bc3cc581931 . I think after the refactoring, this issue should probably not be in relation with this issue. So open a new issue If you have any issue with the upgrade
