### ISSUE TITLE
500 error, not sure how to fix

### ISSUE THREAD

**Issue by liminalitythree** [YunoHost-Apps/gogs_ynh#33]
I think it has something to do with the LDAP or user sign in. When a user is signed in to yunohost it shows a 500 error and does not load. When you're not signed in it works fine. Also, when you try to sign via the gogs site it gives a 500 error on any username/password, even wrong ones. Could it be not connecting to the ldap server?

I tried to find logs but the only thing I could find is with journalctl and it was just gogs saying it had a 500 error, no other information.

**Comment by LeOSW42** [comment]
Hi,

I have similar issue in my fresh install (fresh YNH with fresh Gogs).
In fact, once logged in, I only have a blank page. The error code can be seen by analyzing the HTML page header.

I have that error in **/var/log/gogs/gogs.log** :

    2017/12/06 15:33:48 [...ules/context/repo.go:167 func1()] [E] GetUserByName: user does not exist [uid: 0, name: leo]

Léo

**Comment by LeOSW42** [comment]
In fact, the gogs app bundled in the community app repository is not updated at all. You'll have to check that the gogs installed is in 0.11 version or use the git url directly.

**Comment by raphaeljolivet** [comment]
It's a pitty that the apps are not updated.
What is the process to have them up to date ?
Do you need to do some kind of request ?
Is it based on the CI status ?

**Comment by Josue-T** [comment]
Hello,

I'm working on a big refactoring of this app. So just wait some days what this will be available.

**Comment by Josue-T** [comment]
Hello,

I have pushed a new version available here : https://github.com/YunoHost-Apps/gogs_ynh/tree/refactoring

You can try it if you want and say me if you have the same issue.

**Comment by raphaeljolivet** [comment]
Hi, 
Actually, the problem was fixed once I updated from git, and before your last refactor.
The app seems to run well.

What does your last changes bring ?

BTW, thanks for your work.
A private git repo is a must-have for a geek box.

**Comment by Josue-T** [comment]
I did a lot of changes. All change are available here : https://github.com/YunoHost-Apps/gogs_ynh/pull/36
The most important change is probably the refactoring of all script and the update from upstream.
