### ISSUE TITLE
Error Redirect

### ISSUE THREAD

**Issue by stilobique** [YunoHost-Apps/gogs_ynh#37]
Hi,
i'm install the apps without not problem ; but i can use the service, i'm try to clone a repo with a Https and SSH way but all solution give an error.

Https Method:
<code>fatal: unable to update url base from redirection:
  asked for: https://code.stilobique.com/gogs/stilobique/UE4_Try.git/info/refs?service=git-receive-pack
  redirect: https://stilobique.com/yunohost/sso/?r=aHR0cHM6Ly9jb2RlLnN0aWxvYmlxdWUuY29tL2dvZ3Mvc3RpbG9iaXF1ZS9VRTRfVHJ5LmdpdC9pbmZvL3JlZnM/c2VydmljZT1naXQtcmVjZWl2ZS1wYWNr</code>

SSH Method:
<code>fatal: Could not read from remote repository. </code>

With the SSH way, maybe i don't correctly setup the config (i need to check with your readme information), but why the https way don't work ?
I can give more information if needed.
Quickly > Yunohost 2.7.9 ; and use a subdomain.

**Comment by Josue-T** [comment]
Hello,

Did you try to install the refactoring branch : https://github.com/YunoHost-Apps/gogs_ynh/tree/refactoring

**Comment by stilobique** [comment]
Alright, i'm try that when i can ! Thanks

**Comment by stilobique** [comment]
Hum, i'm try with your refactoring branch, but same error ; i'm try without a subdomain and yes, it's working (with the https).

**Comment by Josue-T** [comment]
Hello,

So if I have really underdstand : It work with `https://domain.tld/subpath` but not with `https://domain.tld/` (on domain root) ?

**Comment by stilobique** [comment]
Hi,
my english are not really good, sorry if i'm not clear ^^ . 
Well, i'm try with this configuration <code>https://domain.tld/apps</code> ; and yes it's ok -only an issue with the SSH setup, but it's my false, not about the apps (i think) ; however, i want use this url <code>https://sub.domain.tld/apps</code>, for <code>https://code.stilobique.com/apps</code> and this way don't work, the Git show me the previous message.

**Comment by Josue-T** [comment]
Hello,

Did you install the app as public or as privat ? Because while I see a redirection to the sso it look like a problem about the sso and mybe with the privat mode.

Maybe could you give the the content of `/etc/ssowat/conf.json` ?

Could you give me also the content of `/var/log/gogs/gogs.log` ?

**Comment by stilobique** [comment]
Hi,
sorry about the time to give a answer ; i'm busy with a lot of job.

I'm reinstall yours apps with your latest version, it's functionnal with my subdomains ! I need to look the SSH fix -my public key has not functional i thinks ! But this ticket can be closed.
Thnaks for your work.

**Comment by Josue-T** [comment]
About ssh, you need to add your public key in your gogs profile (generally in : `https://domain.tld/subpath/user/settings/ssh`). And after user for the authentication need to be gogs. So your ssh connection should look like something like gogs@domain.tld
