### ISSUE TITLE
Can't disconnect using the disconnect button of gogs

### ISSUE THREAD

**Issue by Kcchouette** [YunoHost-Apps/gogs_ynh#40]
1. Connect using sso of YunoHost
 1. Going to your Gogs instance: you're immediatly connected with your account
 1. Click on disconnect: see it **doesn't disconnect** you from Gogs and from sso of yunohost (it's the bug!)
 1. Going to yunohost and click on disconnect: it disconnects you from sso of yunohost and gogs (so this is ok)

**Comment by Josue-T** [comment]
Yes and no, I'm not really sure that it's possible to be disconnected from the sso if you click on the logout button on gogs.
I would just say, just use the yunohost button on the sso to be disconnected

**Comment by Kcchouette** [comment]
@Josue-T: nextcloud does it, see https://github.com/YunoHost-Apps/nextcloud_ynh/pull/115/files for example

**Comment by Josue-T** [comment]
Yes but nextcloud is written in php so it's easy to patch. Gogs is written in go and we use a package witch is already built so we can't patch it.

But if you want to implement it and it work I will merge your purpose.

In all case my point of view is that it's not a really important features so I won't take too much time to implement that.
